### ISSUE TITLE
Line break im HTML-Code, wenn man im Backend eingeloggt ist

### ISSUE THREAD

**Issue by arno1979** [agoat/contao-piwikanalytics#1]
Hallo,
mir ist gerade aufgefallen, dass piwikanalytics folgenden Code ins Frontend-HTML schreibt, wenn man gleichzeitig in einem anderen Tab im Backend eingeloggt ist:
`<!-- PiwikTrackingTag: Tracking users disabled -->\n`
Ist ja im Prinzip eine gute Info, aber der Line break ("\n") am Ende wird bei mir einfach als Text in der gerenderten Seite mit ausgegeben. Was natürlich unschön ist.
Wenn ich das richtig sehe kommt der Code aus `classes/Piwik.php` Zeilen 27 bzw. 29:
`$jsTag = '<!-- PiwikTrackingTag: Tracking users disabled -->\n';`
`$jsTag = '<!-- PiwikTrackingTag: Tracking members disabled -->\n';`

Wenn man den Code so schreibt
`$jsTag = '<!-- PiwikTrackingTag: Tracking users disabled -->'."\n";`
hat man kein Problem, diese Line breaks und auch die Return carriages ("\r") müssen immer in doppelten Anführungszeichen eingefügt werden. Frage mich nicht warum...

Lieben Dank auf jeden Fall für die schöne Erweiterung und wäre super, wenn du das anpassen könntest!

Arno

**Comment by agoat** [comment]
Fixed in 4a461b6b674609008a34f28fa2c955a33987c172

**Comment by arno1979** [comment]
Hallo,
ich habe gestern über den Composer in einer Contao Installation 3.5.19 die Erweiterung mal wieder installiert und war überrascht: Dort wird mir als neuste die Version 3.5.4.9009 angeboten, die hat aber natürlich den Bugfix noch gar nicht drin. Kannst du das Paket im Composer auch noch aktualisieren?

Lieben Dank und viele Grüße
Arno

**Comment by agoat** [comment]
Du hast den Composer-Client installiert, oder?
Im Extension Repository ist die neueste Version veröffentlicht. Der Packagist Server für die contao-legacy/extensions wird von der Contao Community Alliance betrieben und holt sich die Extensions vom Contao ER. Da habe ich keinen Einfluss drauf. Normalerweise sollten Änderungen innerhalb von 15min auch auf dem Legacy-Packagist-Server zu sehen sein.
Ich hab auch gesehen, das einige andere Erweiterungen von mir nicht mit der aktuellsten Version auf dem Packagist-Server vorhanden sind.

Am besten du schreibst eine Nachricht an die CCA. 

Ich selbst verwende nur noch Contao 4 und bei Contao 3 hat bei mir die richtig der Composer Client funktioniert so das ich ihn nicht verwende. Daher ist mir das auch nicht aufgefallen.

**Comment by arno1979** [comment]
Ja, ich verwende den Composer-Client.
Alles klar, dieser Ablauf von ER zu Packagist war mir nicht klar. Dann werde ich die CCA mal kontaktieren. Lieben Dank für die schnelle Antwort!
