### ISSUE TITLE
Falsche deutsche Bezeichnungen für "Ignore Users" und "Ignore Members"

### ISSUE THREAD

**Issue by nkirstein** [agoat/contao-piwikanalytics#3]
In der deutschen Sprachdatei (tl_page.xlf) sind die Bezeichnungen für die Optionen `piwikIgnoreUsers` und `piwikIgnoreMembers` genau falsch herum: User werden als Mitglieder bezeichnet und Members als Benutzer. Außerdem steht dort beide Male "... die im Backend eingeloggt sind", was ja nur für User/Benutzer zutrifft. 

Die korrekten deutschen Übersetzungen müssten lauten:

```
<trans-unit id="tl_page.piwikIgnoreMembers.0">
   <target>Mitglieder ignorieren</target>
</trans-unit>
<trans-unit id="tl_page.piwikIgnoreMembers.1">
   <target>Mitglieder, die im Frontend eingeloggt sind, werden ignoriert und nicht getrackt.</target>
</trans-unit>
<trans-unit id="tl_page.piwikIgnoreUsers.0">
   <target>Benutzer ignorieren</target>
</trans-unit>
<trans-unit id="tl_page.piwikIgnoreUsers.1">
   <target>Benutzer, die im Backend eingeloggt sind, werden ignoriert und nicht getrackt.</target>
</trans-unit>
```

(In der englischen Sprachdatei besteht das Problem nicht.)

**Comment by agoat** [comment]
Fixed in 68f9b14288005017530c3195f913ea8f9c6d94f1
